name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install compiler
      run: sudo apt-get install -y build-essential
    - name: Compile Tic-tac-toe.cpp
      run: g++ Tic-tac-toe.cpp -o Tic-tac-toe
    - name: Run the program (optional)
      run: ./Tic-tac-toe
